  name: Checkov Scan

  on:
    push:
      branches:
        - master # Trigger when code is pushed to the dev branch

  permissions:
    security-events: write

  jobs:
    checkov-scan:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'

        - name: Install Checkov
          run: |
            python -m pip install --upgrade pip
            pip install checkov

        - name: Run Checkov Scan
          run: |
            checkov --directory . --output-file checkov-results.sarif --output sarif --download-external-modules true || true

        - name: Upload results
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: checkov-results.sarif
          env:
            GITHUB_REF: refs/heads/master